const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
let markup='',tick,cleared=0;
const context=vm.createContext({document:{getElementById:()=>({set innerHTML(v){markup=v}}),querySelectorAll:()=>[]},setInterval:fn=>(tick=fn,1),clearInterval:()=>cleared++,pulseChoice:()=>{},showSimulation:()=>{},showDayTransition:(_,cb)=>cb()});
vm.runInContext(fs.readFileSync('characters.js','utf8').split('function applyCharacterPresentation')[0]+code,context);
const run=s=>vm.runInContext(s,context);
run('state.started=true;state.money=0;state.battery=0;render()');
assert.equal(run('state.gameOverReason'),'no-choices');
assert.match(markup,/어떤 선택도 실행할 수 없어/);
const snapshot=run('JSON.stringify(state)');run('choose(1,true);startTimer()');assert.equal(run('JSON.stringify(state)'),snapshot);
run('state=fresh();state.started=true;state.money=0;state.battery=4;render()');assert.equal(run('isGameOver()'),false);
run('state.timeLeft=1;startTimer()');tick();assert.equal(run('state.day'),2);assert.equal(run('state.battery'),0);assert.match(run('state.logs[0]'),/시간 초과/);
run('state=fresh();state.started=true;state.event=6;state.battery=2;render()');assert.equal(run('isGameOver()'),true);
run('state=fresh();render()');assert.equal(run('isGameOver()'),false);assert.match(markup,/게임 시작/);
run('state.started=true;state.day=30;state.event=11;choose(0)');assert.equal(run('state.day'),31);assert.equal(run('isGameOver()'),true);
assert.equal((html.match(/function render\(/g)||[]).length,1);
console.log('PASS: all choices blocked, terminal guard, affordable timeout fallback, battery requirements, restart, day 30 ending.');
// Day introductions must describe the day being entered and keep the clock paused.
let introDay, completeIntro, starts=0;
context.showDayTransition=(day,cb)=>{introDay=day;completeIntro=cb};
context.setInterval=fn=>{tick=fn;starts++;return 1};
run('state=fresh();startGame()');
assert.equal(introDay,1);assert.equal(run('state.day'),1);
assert.equal(run('state.transitioning'),true);assert.equal(starts,0);
run('startGame();choose(0)');assert.equal(run('state.day'),1);
completeIntro();assert.equal(run('state.transitioning'),false);assert.equal(starts,1);assert.equal(run('state.timeLeft'),60);
run('choose(0)');assert.equal(introDay,2);assert.equal(run('state.day'),2);assert.equal(run('state.transitioning'),true);
completeIntro();assert.equal(starts,2);
run('state=fresh();startGame()');const staleIntro=completeIntro;run('state=fresh();render()');staleIntro();assert.equal(run('state.started'),false);assert.equal(starts,2);
console.log('PASS: DAY 1 on start, DAY 2 after first choice, timer paused during intro, duplicate start blocked, stale intro ignored.');
run('state=fresh();startGame()');completeIntro();
run('state.selectedResource="water";togglePause()');
assert.equal(run('state.paused'),true);const pausedState=run('JSON.stringify(state)');
tick();run('choose(0)');assert.equal(run('JSON.stringify(state)'),pausedState);
run('togglePause()');assert.equal(run('state.paused'),false);tick();
assert.equal(run('state.timeLeft'),59);assert.equal(run('state.selectedResource'),'water');
assert.match(markup,/식수/);
console.log('PASS: pause blocks timer and choices; resume restarts countdown; resource selection persists.');
